# sensor:
#   - !include common/base-sensor-vcc.yaml
#
#   Bug: funktioniert nicht gleichzeitig mit A0 ...

platform: adc
pin: VCC
#pin: A0
name: "${upper_devicename} VCC Volt"
icon: mdi:flash-outline
